- name: APT | Installation
  apt: name={{ item }}
  with_items:
    - php5-fpm
    - php5-curl
    - php5-gd
    - php5-gmp
    - php5-json
    - php5-ldap
    - php5-sqlite
    - php5-xmlrpc
    - php5-xsl
    - php5-geoip
    - php5-imap
    - php5-intl
    - php5-mcrypt
    - php5-mysqlnd
  when: ansible_pkg_mgr == "apt" and ansible_distribution_version != "16.04"

- name: APT | Installation
  apt: name={{ item }}
  with_items:
    - php7.0-fpm
    - php7.0-curl
    - php7.0-gd
    - php7.0-gmp
    - php7.0-json
    - php7.0-ldap
    - php7.0-sqlite3
    - php7.0-xmlrpc
    - php7.0-xsl
    - php-geoip
    - php7.0-imap
    - php7.0-intl
    - php7.0-mcrypt
    - php7.0-mysqlnd
  when: ansible_pkg_mgr == "apt" and ansible_distribution_version == "16.04"

- name: Fact | fpm configuration directory
  set_fact: "{{item.key}}={{item.value}}"
  with_items:
    - key: fpm_poold
      value: /etc/php5/fpm/pool.d
    - key: fpm_confd
      value: /etc/php5/fpm/conf.d
    - key: php_modules_d
      value: /etc/php5/mods-available
  when: ansible_distribution_version != "16.04"

- name: Fact | fpm configuration directory
  set_fact: "{{item.key}}={{item.value}}"
  with_items:
    - key: fpm_poold
      value: /etc/php/7.0/fpm/pool.d
    - key: fpm_confd
      value: /etc/php/7.0/fpm/conf.d
    - key: php_modules_d
      value: /etc/php/7.0/mods-available
  when: ansible_distribution_version == "16.04"

- name: Activate php modules
  file: "state=link path=\"{{fpm_confd}}/20-{{item }}\" src=\"{{php_modules_d}}/{{ item }}\""
  with_items:
    - mcrypt.ini

- name: Fact | Detect fpm port
  detect_fpm_port: php_poold={{ fpm_poold }} pool_name={{ vhost_domain }}
  register: pool_info

- name: Fact | FPM port
  set_fact: php_fpm_port={{ pool_info.port }}

- name: FPM Configuration
  template: src=fpm.conf.j2 dest={{ fpm_poold }}/{{ vhost_domain }}.conf

