- name: APT | Installation
  apt: name={{ item }}
  with_items:
    - php5-fpm
    - php5-curl
    - php5-gd
    - php5-gmp
    - php5-json
    - php5-ldap
    - php5-sqlite
    - php5-xmlrpc
    - php5-xsl
    - php5-geoip
    - php5-imap
    - php5-intl
    - php5-mcrypt
    - php5-mysqlnd
  when: ansible_pkg_mgr == "apt"

- name: Fact | fpm configuration directory
  set_fact: fpm_poold=/etc/php5/fpm/pool.d/

- name: Fact | Detect fpm port
  detect_fpm_port: php_poold={{ fpm_poold }} pool_name={{ vhost_domain }}
  register: pool_info

- name: Fact | FPM port
  set_fact: php_fpm_port={{ pool_info.port }}

- name: FPM Configuration
  template: src=fpm.conf.j2 dest={{ fpm_poold }}/{{ vhost_domain }}.conf

