- name: facts
  include_tasks: facts.yml

- name: php_fpm_socket
  set_fact:
    php_fpm_socket: "/run/php/{{ php_fpm_poolname }}.sock"
  when: not php_fpm_socket is defined

- name: APT | Installation
  apt:
    name: "{{ php_packages }}"
  when: ansible_pkg_mgr == "apt" 

- name: Activate php modules
  file:
    state: link
    path: "{{fpm_confd}}/{{item.name }}"
    src: "{{php_modules_d}}/{{ item.src }}"
  with_items: "{{ php_enmod }}"
  when: php_enmod is defined
  notify: restart fpm

- name: FPM Configuration
  template:
    src: "fpm.conf.j2"
    dest: "{{ fpm_poold }}/{{ php_fpm_poolname }}.conf"
  notify: restart fpm
